name: 'AWS Deploy via Terraform'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        terraform init
        terraform fmt -check
        terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
